### ISSUE TITLE
consider renaming Github repo

### ISSUE THREAD

**Issue by danmarsden** [deedey/moodle-block_annulab_lrs#1]
Most Moodle github repos use the frankenstyle name within the repo name eg:
moodle-block_progress

You might want to rename this repo from "moodle_annulabLRS" to "moodle-block_annulab_lrs"
using this convention can sometimes make it easier for people who use git to add your plugin to their site.

(Of course this is completely optional - feel free to make a decision not to do this!)

**Comment by deedey** [comment]
You're right, Dan
Thank you for this advice. I followed it
Regards

**Comment by danmarsden** [comment]
cool - I'd just swap the _ to - between moodle_block so moodle-block to match other repos.. :-)
