### ISSUE TITLE
english translations not quite right:

### ISSUE THREAD

**Issue by danmarsden** [deedey/moodle-block_annulab_lrs#10]
$string['annulablrs:addinstance'] = 'Add un block Annulab LRS';
$string['annulablrs:myaddinstance'] = 'Add un block Annulab LRS';

probably should be:
$string['annulablrs:addinstance'] = 'Add a new Annulab LRS block';
$string['annulablrs:myaddinstance'] =  'Add a new Annulab LRS block to dashboard';

**Comment by danmarsden** [comment]
once you've fixed the language translation please upload the updated code to the moodle.org plugins db to let us know the plugin is ready for review again - once that is sorted we should be ready to approve!

**Comment by deedey** [comment]
Hi Dan!
I think the plugin is ready to update its code in Moodle.org.
I'll do that this day .
Great thanks for your corrections and contributions to make it cleanest.
Dey
