### ISSUE TITLE
get_config API instead of DML

### ISSUE THREAD

**Issue by danmarsden** [deedey/moodle-block_annulab_lrs#11]
ideally when requesting information from the config_plugins table you should use the get_config() functions - config is cached so it doesn't end up in a db call to retrieve the information
I'm guessing this line:
 $tincanexist = $DB->count_records_select('config_plugins', 'name = "endpoint" AND value = "http://lrsdata.com/xapi/"');

could be replaced with:
$endpoint = get_config('block_annulab_lrs', 'endpoint');
if ($endpoint == "http://lrsdata.com/xapi/") {
    $tincanexist = true;
}

**Comment by deedey** [comment]
Changes are done.
Thanks Dan!
