### ISSUE TITLE
consider adding travis support.

### ISSUE THREAD

**Issue by danmarsden** [deedey/moodle-block_annulab_lrs#2]
Adding travis-ci support to your plugin is easy and offers some nice features. More info on adding travis support to your plugin is here:
https://moodle.org/mod/forum/discuss.php?d=323384

**Comment by deedey** [comment]
I'm going to study this Dan, but it appear a bit complicated.
Do I have time to do it later after publication for another version eventually?

**Comment by danmarsden** [comment]
it's actually easier than you might think...

short version...
grab this file:
https://github.com/moodlerooms/moodle-plugin-ci/blob/master/.travis.dist.yml
rename it as .travis.yml and put in the root of your github directory.
Go to: 
https://travis-ci.org/profile/deedey
Flick the switch on the moodle-block_annulab_lrs 

then on every commit you make to github it will fire off a request to travis to run the tests in .travis.yml and will give you traffic lights beside each commit and generate a report.

something else you might want to change:
in .travis.yml the default file has this line:

env:
 global:
  - MOODLE_BRANCH=MOODLE_32_STABLE


you might want to add other branches to that list (or remove 32_STABLE because it's not supported.) so you might want to change it something like:

env:
 global:
  - MOODLE_BRANCH=MOODLE_33_STABLE
  - MOODLE_BRANCH=MOODLE_34_STABLE
  - MOODLE_BRANCH=MOODLE_35_STABLE

doing it now makes it much easier for us to review your code.

**Comment by deedey** [comment]
It's work fine!
Thank you Dan for your suggest. I did know that for all.
 I'll learn about Travis probably in this summer.

**Comment by danmarsden** [comment]
Great! - I see you've fixed some of the reported issues already! - A lot more of those will be fixed when you add the standard boilerplate to the top of the php files.
