### ISSUE TITLE
get_content() function is called twice.

### ISSUE THREAD

**Issue by danmarsden** [deedey/moodle-block_annulab_lrs#4]
When Moodle blocks are loaded on a page, the function get_content() is always called twice. For this reason blocks will store the result of get_content() in a var called $this->content and will check to see if $this->content contains any information before performing the work.

here's an example from an existing block:
https://github.com/moodle/moodle/blob/master/blocks/completionstatus/block_completionstatus.php#L51

hopefully that makes sense. but let me know if you need further clarification.

**Comment by deedey** [comment]
I've added this test
       if ($this->content !== null) {
            return $this->content;
        }

**Comment by danmarsden** [comment]
looks good.
