### ISSUE TITLE
HTTP_HOST is not reliable

### ISSUE THREAD

**Issue by danmarsden** [deedey/moodle-block_annulab_lrs#5]
HTTP_HOST comes from the client and can be spoofed - I'm not sure exactly what you are doing there but you might be wanting to use the variable $CFG->wwwroot instead?
https://github.com/deedey/moodle_annulabLRS/blob/master/block_annulab_lrs.php#L53

**Comment by deedey** [comment]
Yes! I meaned "$CFG->wwwroot" et repaired this.

**Comment by danmarsden** [comment]
cool.
