### ISSUE TITLE
should this use fullname() function

### ISSUE THREAD

**Issue by danmarsden** [deedey/moodle-block_annulab_lrs#6]
https://github.com/deedey/moodle_annulabLRS/blob/master/block_annulab_lrs.php#L51

Typically when displaying a users name we use fullname($USER) - this takes into account site settings, language including preferred names - some languages display the firstname last. This might not be supported by annulablrs though - so feel free to close as won't fix if annulab needs firstname and then lastname to be passed.

**Comment by deedey** [comment]
You're right. I forgot  this option and repaired this with the native parameter fullname($USER)
Thank you

**Comment by danmarsden** [comment]
cool
