### ISSUE TITLE
php close tags should not be included

### ISSUE THREAD

**Issue by danmarsden** [deedey/moodle-block_annulab_lrs#7]
https://github.com/deedey/moodle_block_annulab_lrs/blob/master/version.php#L8

Moodle coding guidelines state that end tags shouldn't be added

**Comment by danmarsden** [comment]
- that version.php file is also missing the gpl boilerplate that would be good to add.

**Comment by deedey** [comment]
I've removed end tags of version.php

**Comment by danmarsden** [comment]
you should probably check all files - you're also still missing the gpl boilerplate on version.php - all php files are supposed to have the boilerplate that starts:
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
... etc

**Comment by deedey** [comment]
It works
