### ISSUE TITLE
pluginname incorrect

### ISSUE THREAD

**Issue by danmarsden** [deedey/moodle-block_annulab_lrs#8]
https://github.com/deedey/moodle_block_annulab_lrs/blob/master/lang/en/block_annulab_lrs.php

the "pluginname" should really be something like "Annulab LRS Block" 

also make sure you remove the php close tag from that file and add the gpl boilerplate to the top.

**Comment by deedey** [comment]
Thank you this comment Dan
I've changed the "pluginname"  to "Annulab LRS Block" and I've removed End Tag

**Comment by danmarsden** [comment]
doesn't look like you have pushed the commit for that change?
https://github.com/deedey/moodle-block_annulab_lrs/blob/master/lang/en/block_annulab_lrs.php

I still see "My own data" instead of "Annulab LRS" - now that I am thinking clearly - it probably doesn't need to contain the word "Block" like I mentioned - typically users will see it in a list of blocks so "Annulab LRS" is probably sufficient :-)

**Comment by deedey** [comment]
As you suggest it, I've changed in all script lang  "My own data" to  "Annulab LRS"
