### ISSUE TITLE
lang string missing

### ISSUE THREAD

**Issue by danmarsden** [deedey/moodle-block_annulab_lrs#9]
no lang string for the capability block/annulab_lrs:myaddinstance

**Comment by deedey** [comment]
I've added this line into en & fr lang:
$string['annulablrs:myaddinstance'] = 'Add un block My own Datas';
I think you mean that, Dan

**Comment by danmarsden** [comment]
yep that's the one. Don't wait for me to close/verify any of these issues - just close them when you think you've sorted them
